# Generated by Django 5.1.3 on 2024-12-26 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BypassRequistion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('predict_to_work_date', models.DateField()),
                ('work_id', models.CharField(max_length=50)),
                ('work_name', models.CharField(max_length=50)),
                ('contractor', models.CharField(max_length=50)),
                ('other_message', models.TextField()),
                ('excute_date', models.DateTimeField()),
                ('reset_date', models.DateTimeField()),
                ('applier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applier', to=settings.AUTH_USER_MODEL)),
                ('excutor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excutor', to=settings.AUTH_USER_MODEL)),
                ('reseter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bypass_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('requistion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bypass_manage.bypassrequistion')),
            ],
        ),
    ]
